# Generated by Django 5.1.1 on 2026-02-18 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('choix_a', models.CharField(max_length=300)),
                ('choix_b', models.CharField(max_length=300)),
                ('choix_c', models.CharField(max_length=300)),
                ('choix_d', models.CharField(max_length=300)),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explication', models.TextField(blank=True)),
                ('points', models.IntegerField(default=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.categorie')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_repondus', models.IntegerField()),
                ('bonnes_reponses', models.IntegerField()),
                ('score_total', models.IntegerField()),
                ('pourcentage', models.FloatField()),
                ('temps_employe', models.IntegerField(default=0)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_tentative'],
            },
        ),
    ]
