# Generated by Django 5.1.1 on 2026-02-18 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativequiz',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='question',
            name='categorie',
        ),
        migrations.AddField(
            model_name='tentativequiz',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
