# Generated by Django 5.1.1 on 2026-02-18 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaitCulturel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fait culturel',
                'verbose_name_plural': 'Faits culturels',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('choix_a', models.CharField(max_length=300)),
                ('choix_b', models.CharField(max_length=300)),
                ('choix_c', models.CharField(max_length=300)),
                ('choix_d', models.CharField(max_length=300)),
                ('bonne_reponse', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explication', models.TextField(blank=True)),
                ('fait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='culture.faitculturel')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=3)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('fait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.faitculturel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_culture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_tentative'],
            },
        ),
    ]
